services:
  gif-bot:
    container_name: memes-bot
    image: git.goyban.com/goyban/bot_meme:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DB_PATH: /data/media.db
    volumes:
      - ./bot_db:/data
